/**
 * Catálogo editable de situaciones.
 *
 * Para agregar una situación, copiá un objeto completo y cambiá:
 * - id: identificador único.
 * - minSeason / maxSeason: temporadas en las que puede aparecer (1–10).
 * - minLevel / maxLevel: niveles permitidos (0–10).
 * - choices[].chance: probabilidad interna de éxito; no se muestra al jugador.
 * - successElo / failureElo: puntos que se acumulan sobre el ELO base del nivel.
 */
export const careerEvents = [
 {id:'birthday-debut',minSeason:1,maxSeason:1,minLevel:0,maxLevel:10,title:'El cumpleaños y el debut',text:'El club organiza un torneo importante justo la noche del cumpleaños de tu hermana. Tu familia ya reservó la mesa.',choices:[
  {id:'play',label:'Jugar el debut',description:'Pedís perdón y corrés al club.',chance:65,successElo:30,failureElo:-12,successTitle:'Una noche inolvidable',successText:'Ganás una partida imposible y llegás al brindis con el trofeo bajo el brazo.',failureTitle:'Ni partida ni torta',failureText:'Perdés rápido y cuando llegás ya apagaron las velitas.'},
  {id:'family',label:'Elegir a la familia',description:'Le explicás a tu instructor que esta vez no podés.',chance:85,successElo:12,failureElo:-8,successTitle:'El ajedrez también sabe esperar',successText:'El instructor valora que hayas hablado de frente y te reserva el tablero para el próximo torneo.',failureTitle:'El tren no espera',failureText:'Otro juvenil ocupa tu lugar y juega tan bien que se queda con el título y el primer tablero del equipo.'}]},
 {id:'first-open-road',minSeason:2,maxSeason:2,minLevel:0,maxLevel:10,title:'La ruta al primer abierto',text:'El torneo empieza temprano y queda a 600 kilómetros. El presupuesto alcanza para una sola comodidad.',choices:[
  {id:'bus',label:'Viajar de noche en micro',description:'Ahorrás plata, pero llegás directo a la ronda.',chance:55,successElo:28,failureElo:-15,successTitle:'Dormir es para después',successText:'Bajás del micro, tomás un café y jugás la mejor partida de tu vida.',failureTitle:'La cabeza sigue en la ruta',failureText:'Confundís una combinación sencilla después de cabecear frente al tablero.'},
  {id:'hotel',label:'Pagar una noche de hotel',description:'Llegás descansado, aunque volvés sin un peso.',chance:82,successElo:20,failureElo:-7,successTitle:'Descanso bien invertido',successText:'La preparación aparece completa cuando el rival entra en tu variante.',failureTitle:'La almohada no juega',failureText:'Dormiste perfecto. Tanto que te quedó la cabeza en la almohada. Una sorpresa de apertura te deja sin respuestas.'}]},
 {id:'exposed-repertoire',minSeason:3,maxSeason:3,minLevel:0,maxLevel:10,title:'Tu repertorio quedó expuesto',text:'Un rival publicó un video con todas tus partidas. Mañana se enfrentan y seguramente conoce tu apertura favorita.',choices:[
  {id:'switch',label:'Cambiar de apertura',description:'Lo sorprendés, pero salís de terreno conocido.',chance:48,successElo:36,failureElo:-18,successTitle:'Sorpresa total',successText:'El rival consume media hora tratando de recordar una apertura que nunca estudió.',failureTitle:'Territorio desconocido',failureText:'La sorpresa funciona contra los dos: tampoco vos entendés la posición.'},
  {id:'trust',label:'Jugar lo que sabés',description:'Que conozca la apertura no significa que pueda jugarla mejor.',chance:74,successElo:23,failureElo:-11,successTitle:'Conocer no es dominar',successText:'Entrás en la línea publicada y encontrás una mejora sobre el tablero.',failureTitle:'Te estaba esperando',failureText:'El rival reproduce su preparación hasta conseguir una posición ganadora.'}]},
 {id:'master-draw-offer',minSeason:4,maxSeason:10,minLevel:4,maxLevel:10,title:'La oferta del maestro',text:'Un gran maestro te ofrece tablas. La posición parece favorable, pero quedan dos minutos en el reloj.',choices:[
  {id:'reject',label:'Seguir jugando',description:'Buscás la victoria bajo presión.',chance:52,successElo:42,failureElo:-22,successTitle:'El día que volteaste a un gigante',successText:'Encontrás el único golpe táctico y el salón entero rodea tu tablero.',failureTitle:'Dos minutos son muy poco',failureText:'La ventaja se escapa y terminás perdiendo por tiempo.'},
  {id:'draw',label:'Aceptar las tablas',description:'Asegurás el resultado y el prestigio.',chance:95,successElo:15,failureElo:-4,successTitle:'Medio punto que pesa',successText:'El empate contra un gran maestro abre conversaciones en todo el circuito.',failureTitle:'La duda queda picando',failureText:'Después descubrís que tenías una victoria forzada y la noticia también circula.'}]},
 {id:'presidential-first-move',minSeason:5,maxSeason:5,minLevel:0,maxLevel:10,title:'La primera jugada',text:'Arranca el Torneo Nacional y el presidente realiza ceremonialmente tu primer movimiento: 1. e4. Vos preparaste 1. d4. ¿Cambiás el movimiento?',choices:[
  {id:'change',label:'Cambiar a 1. d4',description:'Defender tu preparación.',chance:80,successElo:30,failureElo:-12,successTitle:'Conducir un país no es lo mismo que un tablero',successText:'Corregís la jugada, seguís tu preparación y conseguís una posición ganadora.',failureTitle:'No conocerá de ajedrez, pero conoce a las personas',failureText:'Tu rival esperaba exactamente 1. d4 y entra en una preparación demoledora.'},
  {id:'keep',label:'Mantener 1. e4',description:'Confiar en la intuición presidencial.',chance:80,successElo:30,failureElo:-12,successTitle:'Por algo es el conductor del movimiento político más grande de la historia de Latinoamérica',successText:'La partida toma un rumbo inesperado y tu rival queda fuera de libreto.',failureTitle:'El presidente esperaba valentía',failureText:'El presidente se ofende: “No necesitamos obsecuentes sino personas valientes que se atrevan a hacer los mejores movimientos por la patria”.'}]},
 {id:'sponsor-contract',minSeason:6,maxSeason:6,minLevel:0,maxLevel:10,title:'El contrato del patrocinador',text:'Una marca ofrece pagar todos tus viajes, pero exige que abandones la camiseta del club que te formó.',choices:[
  {id:'sign',label:'Firmar el contrato',description:'La carrera necesita recursos.',chance:76,successElo:32,failureElo:-14,successTitle:'El circuito se abre',successText:'Viajás a tres torneos fuertes y el roce internacional mejora tu juego.',failureTitle:'Un precio demasiado alto',failureText:'El contrato trae obligaciones absurdas y el club siente que le diste la espalda.'},
  {id:'decline',label:'Seguir con el club',description:'Buscás otra forma de financiarte.',chance:58,successElo:38,failureElo:-10,successTitle:'El barrio responde',successText:'Una colecta del club financia el viaje y jugás con todos alentando detrás.',failureTitle:'La cuenta no cierra',failureText:'No reunís lo necesario y perdés una fecha clave del circuito.'}]},
 {id:'shared-preparation',minSeason:7,maxSeason:7,minLevel:0,maxLevel:10,title:'Preparación compartida',text:'Tu compañero de selección te pide el análisis secreto que preparaste. Podrían cruzarse en la última ronda.',choices:[
  {id:'share',label:'Compartir el análisis',description:'El equipo está primero.',chance:68,successElo:27,failureElo:-16,successTitle:'Dos cabezas calculan mejor',successText:'Él encuentra una mejora y juntos construyen una variante mucho más fuerte.',failureTitle:'Tu novedad, en tu contra',failureText:'El sorteo los cruza y usa exactamente esa preparación para vencerte.'},
  {id:'keepPrep',label:'Guardar el secreto',description:'Protegés meses de trabajo.',chance:78,successElo:22,failureElo:-9,successTitle:'La novedad sobrevive',successText:'La estrenás en el momento justo y conseguís un punto decisivo.',failureTitle:'El equipo toma nota',failureText:'Tus compañeros interpretan el silencio como desconfianza y dejan de compartir información.'}]},
 {id:'fever-before-qualifier',minSeason:8,maxSeason:8,minLevel:0,maxLevel:10,title:'Fiebre antes de la selección',text:'Te levantás con fiebre el día del clasificatorio. El médico recomienda descanso, pero no habrá otra oportunidad este año.',choices:[
  {id:'rest',label:'Escuchar al médico',description:'Cuidás la carrera larga.',chance:88,successElo:10,failureElo:-8,successTitle:'El cuerpo también juega',successText:'Te recuperás rápido y una baja inesperada abre otra plaza la semana siguiente.',failureTitle:'La oportunidad pasa',failureText:'Nadie se baja y tenés que esperar un año completo.'},
  {id:'playSick',label:'Jugar igual',description:'Apostás todo a cuatro horas de concentración.',chance:38,successElo:50,failureElo:-25,successTitle:'Una hazaña con fiebre',successText:'Clasificás con una defensa memorable y terminás la partida directo en la cama.',failureTitle:'Las piezas se mueven solas',failureText:'El cansancio gana: dejás una dama en prise en una posición sencilla.'}]},
 {id:'open-microphone',minSeason:9,maxSeason:9,minLevel:0,maxLevel:10,title:'El micrófono abierto',text:'Después de una derrota polémica te preguntan en vivo por la organización del torneo. Todavía estás furioso.',choices:[
  {id:'speak',label:'Decir todo lo que pensás',description:'Vas de frente aunque haya consecuencias.',chance:57,successElo:35,failureElo:-20,successTitle:'Alguien tenía que decirlo',successText:'Otros jugadores se suman y la organización corrige el reglamento.',failureTitle:'La frase recortada',failureText:'El video se viraliza sin contexto y recibís una sanción.'},
  {id:'calm',label:'Responder con calma',description:'Esperás a tener todos los datos.',chance:84,successElo:18,failureElo:-6,successTitle:'Cabeza fría fuera del tablero',successText:'Presentás el reclamo por escrito y el fallo se revisa.',failureTitle:'El silencio también habla',failureText:'La prensa interpreta tu prudencia como falta de carácter.'}]},
 {id:'last-draw-offer',minSeason:10,maxSeason:10,minLevel:0,maxLevel:10,title:'La última oferta de tablas',text:'En la final, aceptar tablas asegura el podio. Rechazarlas te deja luchar por el título, pero también podés terminar sin nada.',choices:[
  {id:'podium',label:'Asegurar el podio',description:'Un resultado histórico ya está al alcance.',chance:96,successElo:24,failureElo:-5,successTitle:'Un lugar en la historia',successText:'El podio confirma tu llegada a la élite y el barrio lo celebra toda la noche.',failureTitle:'El campeón quería más',failureText:'La tranquilidad dura poco: sabías que la posición daba para ganar.'},
  {id:'title',label:'Jugar por el título',description:'No llegaste hasta acá para especular.',chance:44,successElo:65,failureElo:-28,successTitle:'Campeón contra todos los pronósticos',successText:'Rechazás las tablas, encontrás la combinación y levantás la copa.',failureTitle:'Caer de pie',failureText:'La victoria no aparece y terminás fuera del podio, pero nadie olvida la valentía.'}]},

 {id:'blindfold-simultaneous',minSeason:1,maxSeason:3,minLevel:0,maxLevel:3,title:'La exhibición a ciegas',text:'Un club vecino te invita a jugar una simultánea a ciegas. Puede darte visibilidad, pero nunca entrenaste sin mirar el tablero.',choices:[
  {id:'accept',label:'Aceptar la exhibición',description:'Confiás en tu memoria y te exponés ante el público.',chance:45,successElo:40,failureElo:-20,successTitle:'El tablero estaba en tu cabeza',successText:'Recordás cada posición y la exhibición se vuelve noticia.',failureTitle:'Una casilla fuera de lugar',failureText:'Confundís dos posiciones y regalás una dama frente a todos.'},
  {id:'decline',label:'Rechazar por ahora',description:'Preferís practicar antes de mostrarte.',chance:82,successElo:12,failureElo:-6,successTitle:'Preparación antes que espectáculo',successText:'El club respeta tu sinceridad y agenda otra fecha.',failureTitle:'La invitación no vuelve',failureText:'Otro juvenil ocupa el lugar y se lleva la atención.'}]},

 {id:'dubious-gambit',minSeason:2,maxSeason:5,minLevel:1,maxLevel:5,title:'El gambito dudoso',text:'Tu entrenador propone estrenar un gambito agresivo que el motor desaprueba, pero que puede sorprender al favorito.',choices:[
  {id:'play-gambit',label:'Jugar el gambito',description:'Apostás por iniciativa y sorpresa.',chance:42,successElo:45,failureElo:-22,successTitle:'La teoría quedó mirando',successText:'El rival consume todo su tiempo y cae bajo el ataque.',failureTitle:'El peón nunca volvió',failureText:'El ataque se apaga y terminás un peón abajo sin compensación.'},
  {id:'solid-line',label:'Elegir una línea sólida',description:'Priorizás una posición que comprendés.',chance:78,successElo:16,failureElo:-8,successTitle:'La paciencia suma puntos',successText:'Neutralizás al favorito y aprovechás su primer error.',failureTitle:'Demasiado respeto',failureText:'La posición igualada se vuelve pasiva y no encontrás contrajuego.'}]},

 {id:'trainer-change',minSeason:3,maxSeason:6,minLevel:2,maxLevel:6,title:'Cambiar de entrenador',text:'Una entrenadora internacional te ofrece trabajar con vos, pero exige abandonar el método del profesor que te formó.',choices:[
  {id:'new-coach',label:'Aceptar el cambio',description:'Buscás una mirada nueva aunque duela la despedida.',chance:68,successElo:30,failureElo:-14,successTitle:'Una nueva forma de calcular',successText:'El nuevo método corrige debilidades que nadie había detectado.',failureTitle:'Demasiado, demasiado pronto',failureText:'Los cambios te llenan de dudas justo antes del torneo.'},
  {id:'old-coach',label:'Seguir con tu profesor',description:'Confiás en el vínculo construido durante años.',chance:75,successElo:18,failureElo:-10,successTitle:'La confianza también entrena',successText:'El profesor adapta el plan y recuperás tu mejor versión.',failureTitle:'El repertorio se estanca',failureText:'Los rivales ya conocen todas tus ideas habituales.'}]},

 {id:'team-board-order',minSeason:3,maxSeason:7,minLevel:2,maxLevel:7,title:'El primer tablero',text:'El capitán te ofrece jugar en el primer tablero del equipo. El rival será mucho más fuerte y un mal resultado puede costar el match.',choices:[
  {id:'board-one',label:'Aceptar el primer tablero',description:'Tomás la responsabilidad más difícil.',chance:55,successElo:38,failureElo:-18,successTitle:'El equipo juega detrás tuyo',successText:'Sostenés al rival y tu empate permite ganar el match.',failureTitle:'La diferencia se sintió',failureText:'El rival impone su categoría y el equipo queda condicionado.'},
  {id:'board-two',label:'Mantener el segundo tablero',description:'Buscás un emparejamiento más equilibrado.',chance:85,successElo:15,failureElo:-6,successTitle:'Un punto bien elegido',successText:'Ganás tu partida y el plan del capitán funciona.' ,failureTitle:'La cuenta no alcanza',failureText:'El primer tablero pierde y tu resultado no compensa la diferencia.'}]},

 {id:'time-control-choice',minSeason:4,maxSeason:8,minLevel:3,maxLevel:8,title:'Dos torneos, un fin de semana',text:'Coinciden un abierto rápido con premios altos y un torneo clásico ideal para tu preparación. Solo podés jugar uno.',choices:[
  {id:'rapid',label:'Jugar el rápido',description:'Más riesgo, más rivales y premio inmediato.',chance:52,successElo:36,failureElo:-17,successTitle:'Reflejos de campeón',successText:'Encadenás victorias y ganás el abierto por desempate.',failureTitle:'El reloj manda',failureText:'Una serie de apuros de tiempo te deja fuera de los premios.'},
  {id:'classical',label:'Jugar el clásico',description:'Elegís partidas largas y aprendizaje profundo.',chance:81,successElo:20,failureElo:-8,successTitle:'Las horas rinden',successText:'Tu preparación aparece y terminás invicto.',failureTitle:'Una semana para olvidar',failureText:'Dos finales interminables te agotan y perdés la última ronda.'}]},

 {id:'seconds-advice',minSeason:5,maxSeason:9,minLevel:4,maxLevel:9,title:'El consejo del segundo',text:'Minutos antes de una partida decisiva, tu segundo recomienda cambiar toda la preparación porque vio algo preocupante.',choices:[
  {id:'trust-second',label:'Seguir su recomendación',description:'Confiás en su análisis de último momento.',chance:65,successElo:32,failureElo:-16,successTitle:'El detalle que cambió la partida',successText:'La corrección evita una novedad del rival y tomás la iniciativa.',failureTitle:'Preparación improvisada',failureText:'Entrás en una posición que ninguno de los dos comprende bien.'},
  {id:'own-plan',label:'Mantener tu plan',description:'Preferís una preparación conocida y asumís el riesgo.',chance:70,successElo:26,failureElo:-13,successTitle:'La convicción pesa',successText:'El rival evita su propia novedad y tu plan funciona.',failureTitle:'La advertencia era correcta',failureText:'Caés exactamente en la variante que tu segundo había detectado.'}]},

 {id:'streamer-invitation',minSeason:1,maxSeason:10,minLevel:0,maxLevel:10,title:'La invitación del streamer',text:'Un creador famoso te invita a jugar partidas rápidas en vivo la noche anterior a una ronda importante.',choices:[
  {id:'stream',label:'Aceptar la transmisión',description:'Ganás exposición, pero sacrificás descanso.',chance:62,successElo:24,failureElo:-12,successTitle:'La cámara te potencia',successText:'La transmisión suma seguidores y llegás relajado a la ronda.',failureTitle:'Una partida de más',failureText:'Te acostás tarde y al día siguiente calculás con la cabeza pesada.'},
  {id:'study',label:'Apagar la cámara y estudiar',description:'Priorizás la ronda y el sueño.',chance:84,successElo:14,failureElo:-5,successTitle:'Silencio productivo',successText:'Encontrás una idea clave en las partidas de tu rival.',failureTitle:'La oportunidad mediática pasa',failureText:'La invitación no se repite y perdés una vidriera importante.'}]},

 {id:'engine-accusation',minSeason:6,maxSeason:10,minLevel:5,maxLevel:10,title:'Sospecha de asistencia',text:'Tu próximo rival viene jugando con una precisión extraña. Podés pedir controles adicionales antes de sentarte.',choices:[
  {id:'request-check',label:'Pedir controles',description:'Exigís garantías aunque genere tensión.',chance:72,successElo:28,failureElo:-15,successTitle:'Jugar con reglas claras',successText:'La organización refuerza el control y la partida transcurre normalmente.',failureTitle:'Una acusación que pesa',failureText:'No encuentran nada y el ambiente se vuelve hostil.'},
  {id:'just-play',label:'Concentrarte en jugar',description:'Dejás la seguridad en manos de los árbitros.',chance:63,successElo:25,failureElo:-18,successTitle:'El tablero da la respuesta',successText:'Jugás una gran partida y ganás sin entrar en polémicas.',failureTitle:'La duda permanece',failureText:'Perdés una partida extraña y no podés dejar de pensar en lo ocurrido.'}]},

 {id:'preparation-leak',minSeason:7,maxSeason:10,minLevel:6,maxLevel:10,title:'La filtración',text:'Una captura de tu preparación privada aparece en un grupo de jugadores. No sabés cuánto material llegó a tu rival.',choices:[
  {id:'rewrite',label:'Rehacer la preparación',description:'Cambiás el repertorio con muy poco tiempo.',chance:58,successElo:42,failureElo:-21,successTitle:'Una novedad sobre la novedad',successText:'El rival sigue el archivo filtrado y cae en tu nueva idea.',failureTitle:'Demasiados cambios',failureText:'Mezclás variantes y olvidás una jugada básica.'},
  {id:'keep-line',label:'Mantener la línea',description:'Confiás en que comprender vale más que memorizar.',chance:76,successElo:24,failureElo:-12,successTitle:'Saber por qué',successText:'Tu comprensión de la posición supera la preparación rival.',failureTitle:'Todo estaba en el archivo',failureText:'El rival reproduce una refutación hasta conseguir ventaja.'}]},

 {id:'match-conditions',minSeason:8,maxSeason:10,minLevel:8,maxLevel:10,title:'Las condiciones del match',text:'Podés pedir una sala silenciosa y cerrada o aceptar un escenario con público para acercar el ajedrez a más gente.',choices:[
  {id:'quiet-room',label:'Pedir una sala cerrada',description:'Priorizás concentración y control.',chance:86,successElo:20,failureElo:-7,successTitle:'Cada pieza se escucha',successText:'El silencio te permite calcular con precisión durante horas.',failureTitle:'Demasiado aislado',failureText:'La atmósfera fría te quita energía en los momentos críticos.'},
  {id:'public-stage',label:'Jugar frente al público',description:'Aceptás ruido y presión a cambio de una gran vidriera.',chance:60,successElo:45,failureElo:-22,successTitle:'La multitud corea tu nombre',successText:'Convertís la presión en energía y ganás una partida histórica.',failureTitle:'El escenario pesa',failureText:'Cada movimiento provoca murmullos y perdés el hilo de la posición.'}]}
];

